-- Initial NEWS rules only. Runtime reads validation_rules; never overwrite admin changes.
INSERT INTO validation_rules(code,name,data_domain,severity,rule_type,executor_key,rule_config,description,is_active,created_at,updated_at)
VALUES
('NEWS_PAYLOAD_STRUCTURE','News list structure','NEWS','ERROR','FORMAT','NEWS_PAYLOAD_STRUCTURE','{"dataField":"data"}','payload.data must be a non-empty array of objects.',true,now(),now()),
('NEWS_TITLE_REQUIRED','News title present','NEWS','WARNING','NOT_NULL','NEWS_TITLE_REQUIRED','{"dataField":"data","fields":["title","headline"]}','Missing title is a warning; fetching the linked article remains possible.',true,now(),now()),
('NEWS_URL_REQUIRED','News article URL','NEWS','ERROR','FORMAT','NEWS_URL_REQUIRED','{"dataField":"data","fields":["url","link","href"],"schemes":["http","https"]}','Each news item must have an absolute HTTP(S) URL with a host.',true,now(),now()),
('NEWS_PUBLISHED_AT_VALID','News publication date','NEWS','WARNING','FORMAT','NEWS_PUBLISHED_AT_VALID','{"dataField":"data","field":"publishedAt","format":"dd/MM/uuuu HH:mm","zone":"Asia/Ho_Chi_Minh"}','When provided, publishedAt must be a valid local date and time.',true,now(),now()),
('NEWS_SYMBOL_MATCH','News source symbol','NEWS','WARNING','RECONCILIATION','NEWS_SYMBOL_MATCH','{"dataField":"data","field":"symbol"}','For symbol-scoped sources, each item symbol must match source_symbol.',true,now(),now()),
('NEWS_URL_DUPLICATE_IN_BATCH','Duplicate URLs within news list','NEWS','WARNING','UNIQUE','NEWS_URL_DUPLICATE_IN_BATCH','{"dataField":"data","fields":["url","link","href"],"schemes":["http","https"],"ignoreQueryPrefixes":["utm_"],"ignoreQueryNames":["fbclid","gclid"]}','Warn on repeated normalized article URLs within this raw payload only.',true,now(),now()),
('NEWS_DUPLICATE_HASH','News duplicate checksum','NEWS','WARNING','UNIQUE','NEWS_DUPLICATE_HASH','{"strategy":"raw-checksum"}','Warn when the same source returns an identical news list; keep the version so new article relationships can still be resolved.',true,now(),now()),
('NEWS_URL_PREVIOUSLY_FETCHED','News URL already fetched','NEWS','WARNING','UNIQUE','NEWS_URL_PREVIOUSLY_FETCHED','{"dataField":"data","fields":["url","link","href"]}','Warn when a listed URL already has NEWS_DATA; the fetch job reuses that content.',true,now(),now()),
('NEWS_DATA_URL_PREVIOUSLY_SEEN','News article data URL already seen','NEWS_DATA','WARNING','UNIQUE','NEWS_DATA_URL_PREVIOUSLY_SEEN','{}','Warn when another NEWS_DATA raw payload has the requested URL; article build resolves links and rejects unchanged repeats.',true,now(),now()),
('NEWS_DATA_METADATA_REQUIRED','News page response metadata','NEWS_DATA','ERROR','NOT_NULL','NEWS_DATA_METADATA_REQUIRED','{}','payload must contain textual boolean, integral http_status, requested_url and final_url strings.',true,now(),now()),
('NEWS_DATA_URL_VALID','News page URLs','NEWS_DATA','ERROR','FORMAT','NEWS_DATA_URL_VALID','{"fields":["requested_url","final_url"],"schemes":["http","https"]}','Validate both page URLs; redirects may change the final URL.',true,now(),now()),
('NEWS_DATA_HTTP_SUCCESS','News page HTTP success','NEWS_DATA','ERROR','RANGE','NEWS_DATA_HTTP_SUCCESS','{"minimum":200,"maximum":299}','Validate the source page HTTP status stored in payload.http_status.',true,now(),now()),
('NEWS_DATA_CONTENT_TYPE_VALID','News HTML content type','NEWS_DATA','ERROR','FORMAT','NEWS_DATA_CONTENT_TYPE_VALID','{"allowed":["text/html","application/xhtml+xml"]}','Require textual=true and an allowed raw_payloads.content_type (ignoring charset).',true,now(),now()),
('NEWS_DATA_RAW_TEXT_REQUIRED','News HTML body present','NEWS_DATA','ERROR','NOT_NULL','NEWS_DATA_RAW_TEXT_REQUIRED','{}','raw_payloads.raw_text must contain non-whitespace source HTML.',true,now(),now()),
('NEWS_DATA_HTML_STRUCTURE','News HTML document','NEWS_DATA','ERROR','FORMAT','NEWS_DATA_HTML_STRUCTURE','{}','Require HTML document markup and parsed visible body text; tolerate recoverable HTML syntax.',true,now(),now()),
('NEWS_DATA_ARTICLE_EXTRACTED','News publisher article extracted','NEWS_DATA','WARNING','NOT_NULL','NEWS_DATA_ARTICLE_EXTRACTED','{}','Validate extracted article fields and body quality; extraction_version is optional provenance and does not determine whether the response can be mapped.',true,now(),now()),
('NEWS_DATA_BLOCK_PAGE_DETECTED','News access block page','NEWS_DATA','WARNING','CUSTOM','NEWS_DATA_BLOCK_PAGE_DETECTED','{"titleMarkers":["access denied","403 forbidden","404 not found","page not found","just a moment","verify you are human","truy cập bị từ chối","không tìm thấy trang"]}','Warn when the page title or h1 identifies an error or access challenge; script tags alone are not errors.',true,now(),now())
ON CONFLICT (code) DO NOTHING;
